import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

@Component({
  selector: 'page-list',
  templateUrl: 'list.html'
})
export class ListPage {
  items = ['ACABAMENTOS EXTERNOS', 'ACABAMENTOS INTERNOS', 'ACESSÓRIOS', 'ALIMENTAÇÃO DE COMBUSTÍVEL',
  'AMORTECEDORES', 'AR CONDICIONADO','ARREFECIMENTO/RESFR. DO MOTOR', 'BANCOS', 'BORRACHAS (GUARNIÇÕES)',
  'CABOS', 'CALOTAS', 'ELÉTRICO', 'EMBLEMAS', 'LETREIROS E FAIXAS', 'EMBREAGEM E CÂMBIO', 'ESCAPAMENTOS',
  'FERRAMENTAS', 'FILTROS', 'FREIO', 'FRISOS', 'GRAMPOS', 'PRESILHAS', 'BUCHAS ETC', 'HIGIENE E LIMPEZA',
  'IGNIÇÃO', 'ILUMINAÇÃO', 'ITENS DE SEGURANÇA', 'LATARIAS', 'MAÇANETAS', 'FECHADURAS ETC', 'MOTOR',
  'PAINEL', 'PÁRA-CHOQUES', 'PARAFUSOS', 'PORCAS E ARRUELAS', 'PNEUS E RODAS', 'PRODUTOS PARA FUNILARIA',
  'RETROVISORES', 'REVESTIMENTOS', 'SOM', 'SUSPENSÃO', 'TAPETES', 'VIDROS' ];

}

